### ISSUE TITLE
Publish in Microsoft Edge Add-ons

### ISSUE THREAD

**Issue by Hirse** [rempl/host-chromium-extension#3]
For nicer installation experience in the new Chromium-based Edge, is it possible to publish this extension in Edge Addons?
https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en-US

**Comment by exdis** [comment]
Hey @Hirse! The extension is being reviewed in Edge Addons 👌 
I'll let you know when it's published.

**Comment by exdis** [comment]
🎉 Published! https://microsoftedge.microsoft.com/addons/detail/rempl/fdjblokocclgcookheppjmfmgfkppmaa
